spring.application.name=palm-recognition-server-app


server.port=8080
spring.datasource.url=jdbc:h2:mem:User
spring.h2.console.enabled=true

middleware.secret=enset
middleware.deviceKey=97e18c08833258668a
middleware.base-url=http://localhost:8190

logging:
    level:
        root: INFO
        enset.ma.palmrecognitionserverapp.services.TimePeriodService: DEBUG